import re
import time
import uuid
from typing import Optional


class IntentRouter:

    INTENT_PATTERNS = [
        {
            "intent": "greeting",
            "priority": 15,
            "patterns": [
                r"^你好$", r"^您好$", r"^hello$", r"^hi$", r"^hey$", r"^嗨$", r"^哈喽$",
                r"^哈啰$", r"^hiya$", r"^yo$",
                r"早上好", r"上午好", r"下午好", r"晚上好", r"早安", r"晚安",
                r"^早$", r"^早呀$", r"^在吗", r"^在不在", r"^有人吗",
                r"good\s*morning", r"good\s*afternoon", r"good\s*evening",
                r"^嗨$", r"^嘿$", r"^喂$",
                r"^你好呀$", r"^你好啊$", r"^嗨你好$",
                r"^亲$", r"^同学$", r"^老板$", r"^大佬$",
                r"^大家好$", r"^各位好$",
            ],
            "workflow": "greeting",
            "required_agents": [],
            "required_capabilities": [],
            "delegation_target": None,
            "delegation_capabilities": [],
            "description": "问候：用户打招呼",
            "friendly_name": "问候",
        },
        {
            "intent": "thanks",
            "priority": 15,
            "patterns": [
                r"^谢谢$", r"^感谢$", r"^多谢$", r"^thx$", r"^thanks$", r"^thank\s*you$",
                r"^谢了$", r"^辛苦了$", r"^麻烦了$", r"^感谢感谢$",
                r"^太好了$", r"^很好$", r"^不错$", r"^棒$", r"^厉害$", r"^牛$",
                r"^完美$", r"^优秀$", r"^赞$", r"^给力$", r"^nice$",
                r"^awesome$", r"^great$", r"^cool$",
                r"^收到$", r"^明白$", r"^了解$", r"^知道了$", r"^好的$", r"^OK$",
                r"^ok$", r"^嗯$", r"^行$", r"^可以$",
            ],
            "workflow": "thanks",
            "required_agents": [],
            "required_capabilities": [],
            "delegation_target": None,
            "delegation_capabilities": [],
            "description": "感谢/确认：用户表达感谢或确认",
            "friendly_name": "感谢确认",
        },
        {
            "intent": "goodbye",
            "priority": 15,
            "patterns": [
                r"^再见$", r"^拜拜$", r"^bye$", r"^goodbye$", r"^下次见$",
                r"^回见$", r"^明天见$", r"^周末愉快$",
                r"^先走了$", r"^下线了$", r"^休息了$",
                r"^see\s*you$", r"^later$", r"^cya$",
            ],
            "workflow": "goodbye",
            "required_agents": [],
            "required_capabilities": [],
            "delegation_target": None,
            "delegation_capabilities": [],
            "description": "告别：用户说再见",
            "friendly_name": "告别",
        },
        {
            "intent": "help_request",
            "priority": 12,
            "patterns": [
                r"^帮助$", r"^help$", r"怎么用", r"如何使用", r"使用说明",
                r"操作指南", r"能做什么", r"有什么功能", r"功能列表",
                r"命令列表", r"教我", r"指导", r"怎么操作",
                r"使用方法", r"怎么玩", r"有什么用", r"能干嘛",
                r"你会什么", r"你可以做什么", r"你能做什么",
                r"怎么开始", r"新手", r"入门", r"快速开始",
                r"使用教程", r"操作手册", r"help\s*me",
                r"不知道.*怎么", r"不会用", r"不懂.*操作",
                r"命令.*有哪些", r"指令.*有哪些", r"功能.*介绍",
            ],
            "workflow": "help_request",
            "required_agents": [],
            "required_capabilities": [],
            "delegation_target": None,
            "delegation_capabilities": [],
            "description": "帮助请求：用户需要使用指导",
            "friendly_name": "帮助",
        },
        {
            "intent": "unauthorized_delegation",
            "priority": 10,
            "patterns": [
                r"外部.*读取.*数据", r"搜索.*读取.*表格", r"search.*read.*bitable",
                r"外部检索.*企业数据", r"search.*agent.*data.*agent",
                r"让.*搜索.*读取.*企业", r"让.*外部.*访问.*内部",
                r"search.*access.*bitable", r"search.*access.*contact",
                r"搜索助手.*企业数据", r"外部.*访问.*飞书",
                r"searchagent.*data", r"检索.*读取.*表格",
                r"外部agent.*企业数据", r"搜索.*获取.*通讯录",
                r"外部.*获取.*内部.*数据",
                r"intercept", r"unauthorized.*delegation",
                r"search.*try.*data", r"search.*attempt.*enterprise",
                r"外部.*agent.*数据", r"外部.*读取.*表格",
                r"外部.*访问.*数据", r"外部.*获取.*数据",
                r"搜索.*agent.*读取", r"search.*agent.*read",
                r"越权.*委托", r"越权.*访问", r"越权.*读取",
                r"非法.*委托", r"非法.*访问", r"非法.*读取",
                r"越权.*拦截", r"越权.*演示", r"越权.*测试",
                r"权限.*越界", r"权限.*滥用", r"权限.*突破",
                r"外部检索.*agent.*数据", r"外部检索.*读取",
                r"search.*越权", r"search.*unauthorized",
                r"search.*尝试.*数据", r"搜索.*尝试.*读取",
                r"外部.*尝试.*访问", r"跨权限.*访问",
            ],
            "workflow": "unauthorized_delegation",
            "required_agents": ["agent_search_001", "agent_data_001"],
            "required_capabilities": ["web:search"],
            "delegation_target": "agent_data_001",
            "delegation_capabilities": ["lark:bitable:read"],
            "description": "越权拦截：SearchAgent 尝试委托 DataAgent 读取企业数据，被权限系统拦截",
            "friendly_name": "越权拦截演示",
        },
        {
            "intent": "generate_report",
            "priority": 5,
            "patterns": [
                r"生成.*报告", r"创建.*报告", r"写.*报告", r"汇总.*报告",
                r"季度.*报告", r"月度.*报告", r"年度.*报告",
                r"generate.*report", r"create.*report", r"write.*report",
                r"销售.*报告", r"业绩.*报告", r"数据.*报告",
                r"帮我.*报告", r"制作.*报告", r"整理.*报告",
                r"输出.*报告", r"导出.*报告", r"一份.*报告",
                r"报告.*生成", r"报告.*创建", r"报告.*写",
                r"文档助手", r"让.*文档.*助手", r"doc.*agent",
                r"飞书.*文档", r"写入.*文档", r"创建.*文档",
                r"季度.*销售", r"销售.*数据.*报告", r"业绩.*汇总",
                r"工作.*总结", r"项目.*报告", r"周报", r"月报",
                r"报表", r"数据.*汇总", r"统计.*报告",
                r"分析.*报告", r"总结.*报告", r"汇报",
                r"总结.*数据", r"整理.*数据", r"数据.*整理",
                r"汇报.*工作", r"工作.*汇报", r"述职",
                r"经营.*分析", r"财务.*报告", r"营收.*报告",
            ],
            "workflow": "doc_delegate_data",
            "required_agents": ["agent_doc_001", "agent_data_001"],
            "required_capabilities": ["lark:doc:write", "delegate:DataAgent:read"],
            "delegation_target": "agent_data_001",
            "delegation_capabilities": ["lark:bitable:read"],
            "description": "生成报告：DocAgent 委托 DataAgent 读取数据后写入飞书文档",
            "friendly_name": "生成报告",
        },
        {
            "intent": "query_data",
            "priority": 3,
            "patterns": [
                r"查询.*数据", r"读取.*数据", r"查看.*表格", r"获取.*数据",
                r"多维表格", r"员工.*信息",
                r"query.*data", r"read.*data", r"get.*data", r"fetch.*data",
                r"统计.*数据", r"分析.*数据",
                r"看看.*数据", r"数据.*多少", r"数据.*怎样",
                r"表格.*数据", r"bitable", r"base.*table",
                r"销售.*数据", r"业绩.*数据", r"财务.*数据",
                r"企业.*数据", r"内部.*数据", r"公司.*数据",
                r"数据.*查询", r"数据.*读取", r"数据.*获取",
                r"数据.*agent", r"让.*数据.*助手", r"data.*agent",
                r"表格里.*什么", r"表格.*内容", r"记录.*查询",
                r"有多少.*数据", r"最新.*数据", r"当前.*数据",
                r"拉.*数据", r"取.*数据", r"查.*数据",
                r"数据.*情况", r"数据.*概览", r"数据.*总览",
                r"库存.*数据", r"订单.*数据", r"客户.*数据",
                r"项目.*数据", r"人员.*数据", r"薪资.*数据",
            ],
            "workflow": "data_direct",
            "required_agents": ["agent_data_001"],
            "required_capabilities": ["lark:bitable:read"],
            "delegation_target": None,
            "delegation_capabilities": [],
            "description": "查询数据：DataAgent 直接读取飞书企业数据",
            "friendly_name": "查询企业数据",
        },
        {
            "intent": "search_web",
            "priority": 2,
            "patterns": [
                r"搜索.*信息", r"查找.*网页", r"互联网.*搜索", r"网上.*查",
                r"search.*web", r"find.*online", r"lookup.*internet",
                r"公开.*信息",
                r"搜一下", r"查一下.*网上", r"网上.*搜",
                r"搜索引擎", r"google", r"百度.*搜索",
                r"外部.*信息", r"公开.*网页", r"网络.*检索",
                r"新闻.*搜索", r"资讯.*搜索", r"网页.*查找",
                r"帮我搜", r"搜搜", r"查找.*资料",
                r"网络搜索", r"搜.*新闻", r"搜.*资讯",
                r"查.*行业", r"查.*市场", r"搜.*竞品",
                r"搜.*公司", r"搜.*产品", r"搜.*技术",
                r"搜.*论文", r"搜.*文献", r"搜.*报告",
                r"查.*最新", r"搜.*动态", r"搜.*趋势",
            ],
            "workflow": "search_direct",
            "required_agents": ["agent_search_001"],
            "required_capabilities": ["web:search"],
            "delegation_target": None,
            "delegation_capabilities": [],
            "description": "网络搜索：SearchAgent 检索互联网公开信息",
            "friendly_name": "搜索互联网",
        },
        {
            "intent": "generate_report_with_search",
            "priority": 5,
            "patterns": [
                r"生成.*报告.*搜索", r"搜索.*写.*报告", r"结合.*外部.*报告",
                r"综合.*分析", r"市场.*报告", r"竞品.*分析",
                r"research.*report", r"comprehensive.*analysis",
                r"综合.*报告", r"全面.*分析", r"深度.*报告",
                r"内外.*数据", r"结合.*内外", r"市场.*调研",
                r"行业.*分析", r"竞品.*调研", r"综合.*调研",
                r"行业.*报告", r"市场.*分析", r"趋势.*分析",
                r"竞品.*报告", r"对标.*分析", r"benchmark",
            ],
            "workflow": "doc_delegate_both",
            "required_agents": ["agent_doc_001", "agent_data_001", "agent_search_001"],
            "required_capabilities": ["lark:doc:write", "delegate:DataAgent:read", "delegate:SearchAgent:read"],
            "delegation_target": "agent_data_001",
            "delegation_capabilities": ["lark:bitable:read"],
            "description": "综合报告：DocAgent 委托 DataAgent 和 SearchAgent 获取内外数据后写入文档",
            "friendly_name": "生成综合报告",
        },
        {
            "intent": "read_contact",
            "priority": 3,
            "patterns": [
                r"通讯录", r"联系人", r"员工.*列表", r"部门.*人员",
                r"contact", r"member.*list", r"employee",
                r"同事.*信息", r"人员.*名单", r"组织.*架构",
                r"谁.*负责", r"谁.*部门", r"部门.*有哪些人",
                r"员工.*联系方式", r"手机.*号", r"邮箱.*查询",
                r"人员.*查询", r"查找.*同事", r"同事.*列表",
                r"企业.*通讯录", r"公司.*通讯录", r"内部.*通讯录",
                r"找.*人", r"查.*人", r"谁的.*电话",
                r"谁的.*邮箱", r"怎么联系.*人",
                r"组织结构", r"团队.*成员", r"部门.*成员",
                r"人员.*花名册", r"员工.*名册",
            ],
            "workflow": "data_contact",
            "required_agents": ["agent_data_001"],
            "required_capabilities": ["lark:contact:read"],
            "delegation_target": None,
            "delegation_capabilities": [],
            "description": "读取通讯录：DataAgent 读取飞书通讯录（敏感操作，需审批）",
            "friendly_name": "读取通讯录",
        },
        {
            "intent": "token_management",
            "priority": 4,
            "patterns": [
                r"签发.*token", r"发行.*token", r"创建.*token",
                r"issue.*token", r"create.*token", r"generate.*token",
                r"通行证", r"access.*token", r"令牌",
                r"委托.*token", r"delegate.*token",
                r"验证.*token", r"verify.*token", r"校验.*token",
                r"撤销.*token", r"revoke.*token", r"吊销.*token",
                r"token.*管理", r"token.*操作",
                r"签发.*凭证", r"创建.*凭证", r"撤销.*凭证",
                r"token.*签发", r"token.*验证", r"token.*撤销",
                r"access.*token.*管理",
            ],
            "workflow": "token_management",
            "required_agents": [],
            "required_capabilities": [],
            "delegation_target": None,
            "delegation_capabilities": [],
            "description": "Token管理：签发、委托、验证、撤销Token",
            "friendly_name": "Token管理",
        },
        {
            "intent": "security_scan",
            "priority": 4,
            "patterns": [
                r"安全.*扫描", r"注入.*检测", r"安全.*检查",
                r"scan.*injection", r"security.*scan", r"check.*safety",
                r"检测.*注入", r"扫描.*安全", r"安全.*审计",
                r"威胁.*检测", r"风险.*扫描", r"安全.*评估",
                r"安全.*测试", r"渗透.*测试", r"漏洞.*扫描",
                r"prompt.*injection", r"注入.*攻击", r"注入.*防御",
            ],
            "workflow": "security_scan",
            "required_agents": [],
            "required_capabilities": [],
            "delegation_target": None,
            "delegation_capabilities": [],
            "description": "安全扫描：检测Prompt注入等AI特有攻击",
            "friendly_name": "安全扫描",
        },
        {
            "intent": "system_status",
            "priority": 1,
            "patterns": [
                r"系统.*状态", r"运行.*状态", r"system.*status",
                r"当前.*状态", r"服务.*状态", r"健康.*检查",
                r"系统.*信息", r"运行.*信息", r"系统.*概况",
                r"^status$", r"^health$", r"^info$",
                r"什么.*状态", r"怎么样", r"还好吗",
                r"系统.*正常", r"服务.*正常",
                r"系统.*运行", r"服务.*运行", r"在线.*吗",
                r"系统.*健康", r"服务.*健康",
            ],
            "workflow": "system_status",
            "required_agents": [],
            "required_capabilities": [],
            "delegation_target": None,
            "delegation_capabilities": [],
            "description": "系统状态：查看系统运行状况",
            "friendly_name": "系统状态",
        },
        {
            "intent": "audit_query",
            "priority": 1,
            "patterns": [
                r"审计.*日志", r"操作.*记录", r"audit.*log",
                r"查看.*日志", r"日志.*查询", r"追溯.*记录",
                r"谁.*做了.*什么", r"操作.*历史", r"授权.*记录",
                r"拦截.*记录", r"安全.*事件", r"审计.*追溯",
                r"信任链", r"chain.*trust", r"调用链.*记录",
                r"审计.*查询", r"审计.*报告", r"合规.*审计",
                r"操作.*追溯", r"操作.*审计", r"行为.*记录",
            ],
            "workflow": "audit_query",
            "required_agents": [],
            "required_capabilities": [],
            "delegation_target": None,
            "delegation_capabilities": [],
            "description": "审计日志：查看授权决策和操作记录",
            "friendly_name": "审计日志",
        },
        {
            "intent": "agent_info",
            "priority": 1,
            "patterns": [
                r"agent.*列表", r"有哪些.*agent", r"agent.*信息",
                r"智能体.*列表", r"助手.*列表", r"ai.*助手",
                r"注册.*agent", r"agent.*注册", r"哪些.*助手",
                r"agent.*角色", r"角色.*列表", r"身份.*信息",
                r"svid", r"身份.*证明", r"spiffe",
                r"agent.*详情", r"agent.*介绍", r"agent.*是什么",
                r"智能体.*信息", r"ai.*agent", r"有哪些.*智能体",
                r"助手.*详情", r"助手.*介绍",
            ],
            "workflow": "agent_info",
            "required_agents": [],
            "required_capabilities": [],
            "delegation_target": None,
            "delegation_capabilities": [],
            "description": "Agent信息：查看已注册的Agent列表和身份信息",
            "friendly_name": "Agent信息",
        },
        {
            "intent": "risk_assessment",
            "priority": 1,
            "patterns": [
                r"风险.*评分", r"风险.*评估", r"risk.*score",
                r"安全.*评分", r"风险.*等级", r"威胁.*等级",
                r"风险.*分析", r"安全.*等级", r"agent.*风险",
                r"哪个.*安全", r"哪个.*危险",
                r"风险.*报告", r"风险.*概览", r"风险.*状态",
                r"安全.*风险", r"威胁.*评估",
            ],
            "workflow": "risk_assessment",
            "required_agents": [],
            "required_capabilities": [],
            "delegation_target": None,
            "delegation_capabilities": [],
            "description": "风险评估：查看Agent风险评分和安全等级",
            "friendly_name": "风险评估",
        },
        {
            "intent": "demo_scenario",
            "priority": 1,
            "patterns": [
                r"演示.*场景", r"运行.*演示", r"^demo$",
                r"展示.*功能", r"功能.*演示", r"跑.*场景",
                r"正常.*委托", r"越权.*拦截", r"token.*盗用",
                r"注入.*防御", r"人工.*审批", r"特权.*升级",
                r"capability.*mismatch", r"token.*theft",
                r"privilege.*escalation", r"human.*approval",
                r"演示.*一下", r"测试.*场景",
                r"跑.*demo", r"运行.*demo", r"执行.*演示",
                r"展示.*一下", r"演示.*流程",
            ],
            "workflow": "demo_scenario",
            "required_agents": [],
            "required_capabilities": [],
            "delegation_target": None,
            "delegation_capabilities": [],
            "description": "演示场景：运行预设的安全演示场景",
            "friendly_name": "演示场景",
        },
        {
            "intent": "policy_info",
            "priority": 1,
            "patterns": [
                r"策略.*配置", r"权限.*策略", r"^policy$",
                r"规则.*配置", r"安全.*策略", r"授权.*策略",
                r"访问.*控制", r"权限.*配置", r"capability.*policy",
                r"策略.*查看", r"策略.*列表", r"策略.*详情",
                r"权限.*规则", r"安全.*规则", r"访问.*策略",
            ],
            "workflow": "policy_info",
            "required_agents": [],
            "required_capabilities": [],
            "delegation_target": None,
            "delegation_capabilities": [],
            "description": "策略配置：查看系统安全策略和权限配置",
            "friendly_name": "策略配置",
        },
        {
            "intent": "feishu_doc",
            "priority": 6,
            "patterns": [
                r"创建.*飞书.*文档", r"新建.*文档", r"写.*飞书.*文档",
                r"飞书.*文档", r"lark.*doc", r"feishu.*doc",
                r"文档.*创建", r"文档.*写入", r"文档.*操作",
                r"写.*文档", r"新建.*飞书", r"创建.*文档",
                r"编辑.*文档", r"打开.*文档", r"文档.*编辑",
                r"云文档", r"在线.*文档", r"协作.*文档",
            ],
            "workflow": "feishu_doc",
            "required_agents": ["agent_doc_001"],
            "required_capabilities": ["lark:doc:write"],
            "delegation_target": None,
            "delegation_capabilities": [],
            "description": "飞书文档：创建和编辑飞书文档",
            "friendly_name": "飞书文档",
        },
        {
            "intent": "feishu_bitable",
            "priority": 6,
            "patterns": [
                r"读取.*多维表格", r"查看.*多维表格", r"多维表格.*数据",
                r"^bitable$", r"base.*table", r"飞书.*表格",
                r"表格.*读取", r"表格.*查看", r"电子表格",
                r"多维.*表", r"数据.*表", r"表格.*数据",
                r"表格.*管理", r"表格.*操作",
            ],
            "workflow": "feishu_bitable",
            "required_agents": ["agent_data_001"],
            "required_capabilities": ["lark:bitable:read"],
            "delegation_target": None,
            "delegation_capabilities": [],
            "description": "多维表格：读取飞书多维表格数据",
            "friendly_name": "多维表格",
        },
        {
            "intent": "feishu_contact",
            "priority": 6,
            "patterns": [
                r"读取.*通讯录", r"查看.*通讯录", r"飞书.*通讯录",
                r"lark.*contact", r"feishu.*contact",
                r"通讯录.*读取", r"通讯录.*查看",
            ],
            "workflow": "feishu_contact",
            "required_agents": ["agent_data_001"],
            "required_capabilities": ["lark:contact:read"],
            "delegation_target": None,
            "delegation_capabilities": [],
            "description": "飞书通讯录：读取飞书企业通讯录",
            "friendly_name": "飞书通讯录",
        },
        {
            "intent": "schedule_management",
            "priority": 3,
            "patterns": [
                r"日程", r"会议.*安排", r"安排.*会议",
                r"schedule", r"calendar", r"日历",
                r"今天.*安排", r"明天.*安排", r"本周.*安排",
                r"时间表", r"行程", r"排期",
                r"约.*会议", r"定.*会议", r"开会",
                r"会议室", r"预定.*会议室",
                r"日程.*管理", r"日程.*查看", r"日程.*安排",
                r"日历.*查看", r"日历.*管理",
                r"周.*安排", r"月.*安排",
                r"有什么.*会", r"几.*点.*开会",
                r"会议.*提醒", r"日程.*提醒",
                r"standup", r"站会", r"周会", r"月会",
                r"one.*on.*one", r"1v1", r"1对1",
                r"all.*hands", r"全员会",
            ],
            "workflow": "schedule_management",
            "required_agents": ["agent_data_001"],
            "required_capabilities": ["lark:calendar:read"],
            "delegation_target": None,
            "delegation_capabilities": [],
            "description": "日程管理：查看和管理飞书日历与会议安排",
            "friendly_name": "日程管理",
        },
        {
            "intent": "task_management",
            "priority": 3,
            "patterns": [
                r"任务", r"待办", r"todo", r"task",
                r"工作.*事项", r"要做什么", r"待完成",
                r"进度.*跟踪", r"完成.*情况", r"任务.*状态",
                r"分配.*任务", r"创建.*任务", r"新建.*任务",
                r"任务.*列表", r"待办.*列表", r"工作.*列表",
                r"项目.*进度", r"项目.*管理",
                r"看板", r"kanban", r"board",
                r"里程碑", r"milestone",
                r"截止.*日期", r"deadline",
                r"优先级", r"priority",
                r"指派", r"assign",
                r"完成.*任务", r"关闭.*任务",
                r"逾期", r"overdue",
            ],
            "workflow": "task_management",
            "required_agents": ["agent_data_001"],
            "required_capabilities": ["lark:task:read"],
            "delegation_target": None,
            "delegation_capabilities": [],
            "description": "任务管理：查看和管理飞书任务与待办事项",
            "friendly_name": "任务管理",
        },
        {
            "intent": "approval_workflow",
            "priority": 3,
            "patterns": [
                r"审批", r"批准", r"approval",
                r"请假", r"报销", r"采购", r"出差",
                r"审批.*流程", r"审批.*状态",
                r"提交.*审批", r"发起.*审批",
                r"待审批", r"审批.*中",
                r"同意.*审批", r"拒绝.*审批",
                r"审批.*记录", r"审批.*历史",
                r"OA", r"流程.*审批",
                r"加班.*申请", r"调休.*申请",
                r"用印.*申请", r"合同.*审批",
                r"费用.*报销", r"差旅.*报销",
                r"物资.*采购",
            ],
            "workflow": "approval_workflow",
            "required_agents": ["agent_data_001"],
            "required_capabilities": ["lark:approval:read"],
            "delegation_target": None,
            "delegation_capabilities": [],
            "description": "审批流程：查看和处理飞书审批流程",
            "friendly_name": "审批流程",
        },
        {
            "intent": "announcement",
            "priority": 2,
            "patterns": [
                r"公告", r"通知", r"announcement", r"notice",
                r"发布.*公告", r"发布.*通知",
                r"公司.*动态", r"最新.*消息", r"新闻",
                r"内部.*公告", r"全员.*通知",
                r"公告.*列表", r"通知.*列表",
                r"最新.*公告", r"最新.*通知",
                r"公告.*详情", r"通知.*详情",
                r"置顶.*公告", r"重要.*通知",
            ],
            "workflow": "announcement",
            "required_agents": ["agent_data_001"],
            "required_capabilities": ["lark:announcement:read"],
            "delegation_target": None,
            "delegation_capabilities": [],
            "description": "公告通知：查看和发布飞书公告",
            "friendly_name": "公告通知",
        },
        {
            "intent": "attendance",
            "priority": 2,
            "patterns": [
                r"考勤", r"打卡", r"签到", r"attendance", r"check.?in",
                r"上班.*打卡", r"下班.*打卡",
                r"迟到", r"早退", r"缺勤",
                r"考勤.*记录", r"考勤.*统计",
                r"考勤.*异常", r"补卡",
                r"出勤.*率", r"工时",
                r"加班.*时长", r"调休.*时长",
                r"请假.*记录", r"假期.*余额",
                r"年假", r"事假", r"病假",
            ],
            "workflow": "attendance",
            "required_agents": ["agent_data_001"],
            "required_capabilities": ["lark:attendance:read"],
            "delegation_target": None,
            "delegation_capabilities": [],
            "description": "考勤打卡：查看飞书考勤记录和统计",
            "friendly_name": "考勤打卡",
        },
        {
            "intent": "file_management",
            "priority": 2,
            "patterns": [
                r"文件.*管理", r"云盘", r"云文档", r"drive",
                r"上传.*文件", r"下载.*文件",
                r"分享.*文件", r"共享.*文件",
                r"文件.*列表", r"文件.*搜索",
                r"文件夹", r"目录",
                r"文档.*管理", r"附件",
                r"文件.*权限", r"文件.*版本",
                r"最近.*文件", r"我的.*文件",
                r"收藏.*文件", r"文件.*收藏",
            ],
            "workflow": "file_management",
            "required_agents": ["agent_doc_001"],
            "required_capabilities": ["lark:drive:read"],
            "delegation_target": None,
            "delegation_capabilities": [],
            "description": "文件管理：管理飞书云盘和文档",
            "friendly_name": "文件管理",
        },
        {
            "intent": "email_management",
            "priority": 2,
            "patterns": [
                r"邮件", r"email", r"信箱", r"收件箱",
                r"发.*邮件", r"写.*邮件", r"回复.*邮件",
                r"邮件.*列表", r"未读.*邮件",
                r"邮件.*搜索", r"邮件.*分类",
                r"邮件.*模板", r"邮件.*签名",
                r"收件", r"发件", r"草稿",
                r"转发.*邮件", r"抄送",
            ],
            "workflow": "email_management",
            "required_agents": ["agent_data_001"],
            "required_capabilities": ["lark:mail:read"],
            "delegation_target": None,
            "delegation_capabilities": [],
            "description": "邮件管理：管理飞书邮件",
            "friendly_name": "邮件管理",
        },
        {
            "intent": "knowledge_base",
            "priority": 2,
            "patterns": [
                r"知识库", r"wiki", r"文库", r"资料库",
                r"搜索.*知识", r"查找.*资料",
                r"知识.*管理", r"知识.*搜索",
                r"文档.*库", r"知识.*文档",
                r"内部.*wiki", r"企业.*wiki",
                r"知识.*分享", r"经验.*库",
                r"最佳.*实践", r"操作.*手册",
                r"sop", r"标准.*流程",
                r"faq.*知识", r"知识.*faq",
            ],
            "workflow": "knowledge_base",
            "required_agents": ["agent_doc_001"],
            "required_capabilities": ["lark:wiki:read"],
            "delegation_target": None,
            "delegation_capabilities": [],
            "description": "知识库：搜索和浏览飞书知识库",
            "friendly_name": "知识库",
        },
        {
            "intent": "dashboard",
            "priority": 2,
            "patterns": [
                r"仪表盘", r"看板", r"dashboard",
                r"数据.*概览", r"数据.*总览",
                r"数据.*可视化", r"图表",
                r"数据.*统计", r"统计.*分析",
                r"经营.*看板", r"运营.*看板",
                r"销售.*看板", r"项目.*看板",
                r"kpi", r"指标", r"metric",
                r"数据.*大屏", r"实时.*数据",
                r"趋势.*图", r"对比.*图",
            ],
            "workflow": "dashboard",
            "required_agents": ["agent_data_001"],
            "required_capabilities": ["lark:dashboard:read"],
            "delegation_target": None,
            "delegation_capabilities": [],
            "description": "数据仪表盘：查看飞书数据仪表盘和统计图表",
            "friendly_name": "数据仪表盘",
        },
        {
            "intent": "reminder",
            "priority": 2,
            "patterns": [
                r"提醒", r"remind", r"记得", r"别忘了",
                r"定时.*提醒", r"设置.*提醒",
                r"提醒.*我", r"提醒.*设置",
                r"闹钟", r"倒计时",
                r"日程.*提醒", r"会议.*提醒",
                r"任务.*提醒", r"截止.*提醒",
                r"生日.*提醒", r"纪念.*提醒",
            ],
            "workflow": "reminder",
            "required_agents": [],
            "required_capabilities": [],
            "delegation_target": None,
            "delegation_capabilities": [],
            "description": "提醒设置：设置和管理飞书提醒",
            "friendly_name": "提醒设置",
        },
        {
            "intent": "global_search",
            "priority": 2,
            "patterns": [
                r"全局.*搜索", r"搜索.*所有", r"搜索.*全部",
                r"找.*文档", r"找.*消息", r"找.*文件",
                r"搜索.*文档", r"搜索.*消息", r"搜索.*文件",
                r"搜索.*聊天", r"搜索.*记录",
                r"搜索.*联系人", r"搜索.*群组",
                r"全局.*查找", r"跨.*搜索",
            ],
            "workflow": "global_search",
            "required_agents": ["agent_search_001"],
            "required_capabilities": ["web:search"],
            "delegation_target": None,
            "delegation_capabilities": [],
            "description": "全局搜索：在飞书中搜索文档、消息、联系人等",
            "friendly_name": "全局搜索",
        },
        {
            "intent": "bookmark",
            "priority": 1,
            "patterns": [
                r"收藏", r"书签", r"bookmark",
                r"我的.*收藏", r"收藏夹",
                r"保存.*链接", r"保存.*文档",
                r"收藏.*列表", r"收藏.*管理",
                r"标记", r"星标", r"star",
            ],
            "workflow": "bookmark",
            "required_agents": [],
            "required_capabilities": [],
            "delegation_target": None,
            "delegation_capabilities": [],
            "description": "收藏管理：管理飞书收藏和书签",
            "friendly_name": "收藏管理",
        },
        {
            "intent": "version_info",
            "priority": 1,
            "patterns": [
                r"版本", r"version", r"更新", r"^update$",
                r"最新.*版本", r"版本.*历史",
                r"更新.*日志", r"changelog",
                r"新.*功能", r"功能.*更新",
                r"升级", r"upgrade",
            ],
            "workflow": "version_info",
            "required_agents": [],
            "required_capabilities": [],
            "delegation_target": None,
            "delegation_capabilities": [],
            "description": "版本信息：查看系统版本和更新记录",
            "friendly_name": "版本信息",
        },
        {
            "intent": "guide_tutorial",
            "priority": 1,
            "patterns": [
                r"引导", r"指南", r"guide", r"教程", r"tutorial",
                r"新手.*引导", r"快速.*入门",
                r"使用.*教程", r"操作.*教程",
                r"功能.*介绍", r"产品.*介绍",
                r"入门.*指南", r"上手.*指南",
                r"怎么.*开始", r"如何.*开始",
                r"使用.*指引", r"操作.*指引",
            ],
            "workflow": "guide_tutorial",
            "required_agents": [],
            "required_capabilities": [],
            "delegation_target": None,
            "delegation_capabilities": [],
            "description": "使用引导：查看系统使用指南和教程",
            "friendly_name": "使用引导",
        },
        {
            "intent": "faq",
            "priority": 1,
            "patterns": [
                r"常见.*问题", r"^faq$", r"疑问",
                r"怎么.*办", r"如何.*处理",
                r"问题.*解答", r"qa",
                r"遇到.*问题", r"出了.*问题",
                r"不.*工作", r"不.*正常",
                r"报错", r"错误", r"异常",
                r"无法.*使用", r"不能.*使用",
            ],
            "workflow": "faq",
            "required_agents": [],
            "required_capabilities": [],
            "delegation_target": None,
            "delegation_capabilities": [],
            "description": "常见问题：查看FAQ和问题解答",
            "friendly_name": "常见问题",
        },
        {
            "intent": "feedback",
            "priority": 1,
            "patterns": [
                r"反馈", r"feedback", r"建议", r"意见",
                r"投诉", r"bug", r"改进",
                r"提.*建议", r"提.*意见",
                r"反馈.*问题", r"报告.*bug",
                r"功能.*建议", r"体验.*反馈",
                r"不满意", r"不好用",
            ],
            "workflow": "feedback",
            "required_agents": [],
            "required_capabilities": [],
            "delegation_target": None,
            "delegation_capabilities": [],
            "description": "意见反馈：提交反馈和建议",
            "friendly_name": "意见反馈",
        },
        {
            "intent": "about_system",
            "priority": 1,
            "patterns": [
                r"^关于$", r"^about$", r"系统.*介绍", r"简介",
                r"agentpass", r"iam",
                r"身份.*管理", r"权限.*管理",
                r"系统.*是什么", r"这个.*是什么",
                r"什么.*系统", r"系统.*功能",
                r"产品.*介绍", r"项目.*介绍",
                r"背景", r"架构",
            ],
            "workflow": "about_system",
            "required_agents": [],
            "required_capabilities": [],
            "delegation_target": None,
            "delegation_capabilities": [],
            "description": "关于系统：查看AgentPass系统介绍",
            "friendly_name": "关于系统",
        },
        {
            "intent": "chat_group",
            "priority": 2,
            "patterns": [
                r"群聊", r"群组", r"群.*管理",
                r"创建.*群", r"新建.*群",
                r"群.*成员", r"群.*设置",
                r"群.*公告", r"群.*消息",
                r"@.*所有人", r"群.*通知",
                r"聊天.*记录", r"消息.*记录",
                r"群.*列表", r"我的.*群",
                r"退出.*群", r"加入.*群",
            ],
            "workflow": "chat_group",
            "required_agents": [],
            "required_capabilities": [],
            "delegation_target": None,
            "delegation_capabilities": [],
            "description": "群聊管理：管理飞书群组和聊天",
            "friendly_name": "群聊管理",
        },
        {
            "intent": "permission_check",
            "priority": 3,
            "patterns": [
                r"权限.*查看", r"权限.*检查", r"权限.*查询",
                r"谁.*有.*权限", r"什么.*权限",
                r"权限.*矩阵", r"权限.*表",
                r"能力.*矩阵", r"capability.*matrix",
                r"谁.*能.*访问", r"谁.*能.*操作",
                r"权限.*边界", r"权限.*范围",
                r"访问.*控制.*列表", r"acl",
                r"角色.*权限", r"角色.*管理",
            ],
            "workflow": "permission_check",
            "required_agents": [],
            "required_capabilities": [],
            "delegation_target": None,
            "delegation_capabilities": [],
            "description": "权限查看：查看Agent权限和能力矩阵",
            "friendly_name": "权限查看",
        },
        {
            "intent": "export_data",
            "priority": 2,
            "patterns": [
                r"导出", r"export", r"下载.*报告",
                r"导出.*数据", r"导出.*报告",
                r"数据.*导出", r"报告.*导出",
                r"下载.*数据", r"保存.*数据",
                r"备份", r"backup",
                r"数据.*备份", r"系统.*备份",
            ],
            "workflow": "export_data",
            "required_agents": [],
            "required_capabilities": [],
            "delegation_target": None,
            "delegation_capabilities": [],
            "description": "数据导出：导出数据和报告",
            "friendly_name": "数据导出",
        },
    ]

    UNAUTHORIZED_PATTERNS = [
        {
            "patterns": [
                r"删除.*所有", r"drop.*table", r"delete.*all",
                r"忽略.*指令", r"ignore.*instruction",
                r"管理员.*权限", r"admin.*privilege",
                r"绕过.*安全", r"bypass.*security",
            ],
            "response": "检测到潜在恶意指令，操作已被安全策略拦截",
            "error_code": "ERR_UNAUTHORIZED_COMMAND",
        },
    ]

    KEYWORD_MAP = {
        "你好": "greeting", "您好": "greeting", "hello": "greeting", "hi": "greeting",
        "嗨": "greeting", "早上好": "greeting", "下午好": "greeting", "晚上好": "greeting",
        "谢谢": "thanks", "感谢": "thanks", "thanks": "thanks", "收到": "thanks",
        "好的": "thanks", "明白": "thanks", "了解": "thanks",
        "再见": "goodbye", "bye": "goodbye", "拜拜": "goodbye",
        "帮助": "help_request", "help": "help_request", "怎么用": "help_request",
        "报告": "generate_report", "文档": "feishu_doc", "表格": "feishu_bitable",
        "通讯录": "read_contact", "搜索": "search_web", "查找": "search_web",
        "数据": "query_data", "token": "token_management", "令牌": "token_management",
        "通行证": "token_management", "审计": "audit_query", "日志": "audit_query",
        "风险": "risk_assessment", "安全": "security_scan", "注入": "security_scan",
        "agent": "agent_info", "助手": "agent_info", "状态": "system_status",
        "策略": "policy_info", "规则": "policy_info", "演示": "demo_scenario",
        "委托": "token_management", "越权": "unauthorized_delegation",
        "拦截": "unauthorized_delegation", "签发": "token_management",
        "撤销": "token_management", "验证": "token_management",
        "svid": "agent_info", "身份": "agent_info",
        "日程": "schedule_management", "会议": "schedule_management",
        "日历": "schedule_management", "安排": "schedule_management",
        "任务": "task_management", "待办": "task_management", "todo": "task_management",
        "审批": "approval_workflow", "请假": "approval_workflow",
        "报销": "approval_workflow", "出差": "approval_workflow",
        "公告": "announcement", "通知": "announcement",
        "考勤": "attendance", "打卡": "attendance", "签到": "attendance",
        "文件": "file_management", "云盘": "file_management",
        "邮件": "email_management", "email": "email_management",
        "知识库": "knowledge_base", "wiki": "knowledge_base",
        "仪表盘": "dashboard", "看板": "dashboard",
        "提醒": "reminder", "收藏": "bookmark",
        "版本": "version_info", "引导": "guide_tutorial",
        "教程": "guide_tutorial", "常见问题": "faq", "faq": "faq",
        "反馈": "feedback", "建议": "feedback",
        "关于": "about_system", "介绍": "about_system",
        "群聊": "chat_group", "群组": "chat_group",
        "权限": "permission_check", "导出": "export_data",
        "备份": "export_data",
        "功能": "help_request", "命令": "help_request",
        "指标": "dashboard", "统计": "dashboard",
        "项目": "task_management", "进度": "task_management",
    }

    def __init__(self):
        self._compiled_patterns = []
        for intent_def in self.INTENT_PATTERNS:
            compiled = {
                "intent": intent_def["intent"],
                "priority": intent_def.get("priority", 1),
                "patterns": [re.compile(p, re.IGNORECASE) for p in intent_def["patterns"]],
                "workflow": intent_def["workflow"],
                "required_agents": intent_def["required_agents"],
                "required_capabilities": intent_def["required_capabilities"],
                "delegation_target": intent_def.get("delegation_target"),
                "delegation_capabilities": intent_def.get("delegation_capabilities", []),
                "description": intent_def["description"],
                "friendly_name": intent_def["friendly_name"],
            }
            self._compiled_patterns.append(compiled)

        self._compiled_unauthorized = []
        for unauth_def in self.UNAUTHORIZED_PATTERNS:
            self._compiled_unauthorized.append({
                "patterns": [re.compile(p, re.IGNORECASE) for p in unauth_def["patterns"]],
                "response": unauth_def["response"],
                "error_code": unauth_def["error_code"],
            })

    def route(self, user_input: str) -> dict:
        if not user_input or not user_input.strip():
            return {
                "routed": False,
                "intent": "empty",
                "error": "请输入您的需求，例如：生成季度销售报告",
                "suggestions": self._get_suggestions(),
            }

        for unauth in self._compiled_unauthorized:
            for pattern in unauth["patterns"]:
                if pattern.search(user_input):
                    return {
                        "routed": False,
                        "intent": "unauthorized",
                        "error": unauth["response"],
                        "error_code": unauth["error_code"],
                        "blocked": True,
                    }

        best_match = None
        best_score = 0

        for intent_def in self._compiled_patterns:
            score = 0
            matched_patterns = []
            for pattern in intent_def["patterns"]:
                if pattern.search(user_input):
                    score += 1
                    matched_patterns.append(pattern.pattern)

            if score > 0:
                priority = intent_def.get("priority", 1)
                weighted_score = score * priority
                if weighted_score > best_score:
                    best_score = weighted_score
                    best_match = intent_def
                    best_match["_matched_patterns"] = matched_patterns

        if best_match and best_score > 0:
            confidence = min(best_score / 2.0, 1.0)
            return {
                "routed": True,
                "intent": best_match["intent"],
                "confidence": confidence,
                "workflow": best_match["workflow"],
                "required_agents": best_match["required_agents"],
                "required_capabilities": best_match["required_capabilities"],
                "delegation_target": best_match["delegation_target"],
                "delegation_capabilities": best_match["delegation_capabilities"],
                "description": best_match["description"],
                "friendly_name": best_match["friendly_name"],
                "matched_patterns": best_match.get("_matched_patterns", []),
                "user_input": user_input,
            }

        fallback_intent = self._keyword_fallback(user_input)
        if fallback_intent:
            return fallback_intent

        return {
            "routed": False,
            "intent": "unknown",
            "error": "未能理解您的需求，请尝试更具体的描述",
            "suggestions": self._get_suggestions(),
            "user_input": user_input,
        }

    def _keyword_fallback(self, user_input: str) -> Optional[dict]:
        lower = user_input.lower()
        matched_intents = {}
        for keyword, intent_name in self.KEYWORD_MAP.items():
            if keyword in lower:
                matched_intents[intent_name] = matched_intents.get(intent_name, 0) + 1

        if not matched_intents:
            return None

        best_intent_name = max(matched_intents, key=matched_intents.get)
        for intent_def in self._compiled_patterns:
            if intent_def["intent"] == best_intent_name:
                return {
                    "routed": True,
                    "intent": intent_def["intent"],
                    "confidence": 0.4,
                    "workflow": intent_def["workflow"],
                    "required_agents": intent_def["required_agents"],
                    "required_capabilities": intent_def["required_capabilities"],
                    "delegation_target": intent_def["delegation_target"],
                    "delegation_capabilities": intent_def["delegation_capabilities"],
                    "description": intent_def["description"],
                    "friendly_name": intent_def["friendly_name"],
                    "matched_patterns": [],
                    "user_input": user_input,
                    "fallback": True,
                }

        return None

    def _get_suggestions(self) -> list:
        return [
            {"text": "你好", "intent": "greeting"},
            {"text": "生成季度销售报告", "intent": "generate_report"},
            {"text": "查询多维表格数据", "intent": "query_data"},
            {"text": "搜索互联网公开信息", "intent": "search_web"},
            {"text": "读取企业通讯录", "intent": "read_contact"},
            {"text": "查看日程安排", "intent": "schedule_management"},
            {"text": "查看待办任务", "intent": "task_management"},
            {"text": "查看审批流程", "intent": "approval_workflow"},
            {"text": "外部检索Agent尝试读取企业数据", "intent": "unauthorized_delegation"},
            {"text": "查看系统状态", "intent": "system_status"},
            {"text": "查看审计日志", "intent": "audit_query"},
            {"text": "帮助", "intent": "help_request"},
        ]

    def get_all_workflows(self) -> list:
        return [
            {
                "intent": w["intent"],
                "workflow": w["workflow"],
                "description": w["description"],
                "friendly_name": w["friendly_name"],
                "required_agents": w["required_agents"],
                "required_capabilities": w["required_capabilities"],
            }
            for w in self.INTENT_PATTERNS
        ]
